Init meeting-form
MarioPierides/capstone-project pull request #4
Opened 2022-05-25 11:55 UTC by MarioPierides

In this pull request I have added a form to create a new meeting - by using React UseState
The form adds a new meeting to the meeting list.

Note: The form and the list are in the same page for now. I will render them in different pages in the future, I'm just not there yet. No styled-components included until now.

2022-05-25 13:10 UTC, F-Kirchhoff requested changes
Wow, I am amazed Mario very clean code all in all. I added some suggestions for semantic and clean code, and you need to add a key to each component in your list when you map your meetings. Oh and please delete your hooks folder with the empty files in it.
But besides that very good job for your first PR! 🚀

2022-05-25 13:10 UTC, F-Kirchhoff commented on package.json
> -    "test": "react-scripts test",
Why did you delete this line?

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +    const titel = event.target.elements.titel.value;
Please stay english: 'title' ;)

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +    setMeetings(prevState => [...prevState, { titel, location, activity }]);
Wow 😲 thats quite advanced!

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +    console.log(activity);
Please remove console.logs before you start a pullrequest ;) 🕵️

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +          </select>
Looking very good, I only would suggest to use the singular here, to stay consistent (you use location in the upper one and not locations)

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +    const location = event.target.elements.location.value;
In a Form component the inputs with a `name` attribute are accessible without the `.elements` object. so you can omit the `.elements` here as well.

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +    console.log(event);
Please delete all console.logs 🕵️

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +            <li>
Here is the problem with vercel: you need to give each list item a unique key prop. 
```suggestion
            <li key={someUniqueKey}>
```
You must not use the index of the meeting but should implement an id in your meeting objects:
```
{
  title,
  location,
  activity,
  id: "1234"
}
```
Hint: you can use `nanoid` for that. You can find it in google.

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/index.js
> +              <div>{meeting.activity}</div>
Please use semantic html here, for example a p tag or a span.

2022-05-25 13:10 UTC, F-Kirchhoff commented on pages/meetings.js
> +}
this page does look empty, please remove it if it does not serve a purpose yet. You can add it in later on.

2022-05-28 10:25 UTC, oy-gen reviewed
Please delete console.log in line 14. Everything else LGTM.

2022-05-28 10:25 UTC, oy-gen commented on pages/index.js
>      console.log(event);
console.log in line 14 is still there, please delete.

2022-05-29 18:53 UTC, merged